#ifndef SYMBOL_H
#define SYMBOL_H
enum class Symbol{
    NONESY, BEGINSY, ENDSY, IFSY,
    THENSY, ELSESY, IDSY, INTSY, DOUBLESY,
    PLUSSY, MINUSSY, STARSY, DIVISY,
    LPARSY, RPARSY, COMMASY, SEMISY,
    COLONSY, ASSIGNSY, EQUSY,
    CONSTSY, VARSY, PROCEDURESY, ODDSY,
    WHILESY, DOSY, CALLSY, REPEATSY,
    UNTILSY, READSY, WRITESY,
    LESSSY, MORESY,
    LESSEQUALSY, MOREEQUALSY, NOTEQUALSY
};

#endif // SYMBOL_H
